spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/forum?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: warn
    com.xsh: info
  file: log/blog-pro.log

server:
  port: 8082
