
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://121.41.169.208:3306/forum?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
#jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    root: info
    com.xsh: debug
  file: log/blog-dev.log

server:
  port: 8081